version: '3.7'
services:

  # Environment
  bank-db:
    image: postgres
    hostname: bank-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - C:\Users\Ashton\IdeaProjects\p_ss_bank_51\p_ss_bank_51\transfer\config\prometheus.yml:/etc/prometheus/prometheus.yml

