server:
  port: 8092
  servlet:
    context-path: /api/transfer
management:
  server:
    port: 8191
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


  metrics:
    tags:
      application=${spring:
        application:
          name}:
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    
  liquibase:
    default-schema: transfer
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: true
  application:
    name: transfer-app
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
